/** Package with an "ICrossMode" interface declaration.
 * 
 *  The interface describes the functionality of Cross Control Unit.
 */

/* Package with an "ICrossMode" interface declaration. */

package traffic_light.ICrossMode

const UInt32 Direction1Red          = 0x0001;
const UInt32 Direction1Yellow       = 0x0002;
const UInt32 Direction1Green        = 0x0004;
const UInt32 Direction1Blink        = 0x0008;

const UInt32 Direction2Red          = 0x0100;
const UInt32 Direction2Yellow       = 0x0200;
const UInt32 Direction2Green        = 0x0400;
const UInt32 Direction2Blink        = 0x0800;


interface {
    /* ICrossMode interface method */
    SetCrossMode(in UInt32 mode, out UInt32 result);
}
