/* Package with an "IEventLog" interface declaration. */

package traffic_light.IEventLog

typedef UInt32 EventCode;

const UInt32 MaxSourceLength = 16;
typedef string<MaxSourceLength> EventSource;

const UInt32 MaxTextLength = 60;
typedef string<MaxTextLength> EventText;

struct EventRecord {
    EventCode code;
    EventSource source;
    EventText text;
}

struct SysHealth {
    EventCode controlSystem;
    EventCode connector;
    EventCode crossChecker;
    EventCode lightsGpio1;
    EventCode lightsGpio2;
    EventCode diagnostics;
}

interface {
    /* IEventMsg interface method */
    Collect(in EventRecord event, out SysHealth state);
}